### PR TITLE
micrortps: The demo micrortps_listener application does not receive a…

### PR DESCRIPTION
**Pull request by SylvainPastor**
…ny sensor data because it does not subscribe to the correct topic.

Action: Documentation update (Creating a Fast DDS Listener application)

### CODE REVIEW

**Comment by TSC21** [comment]
What version of FastRTPS is the FastRTPSGen is fetching/using on your system? Are you using ROS2 on your system? This example targets non-ROS2 systems, so the generated code might actually be different.

**Comment by SylvainPastor** [comment]
Hello @TSC21 

- This example targets non-ROS2 systems: Yes it was understood (The documentation is very clear on this subject)
- What version of FastRTPS is the FastRTPSGen is fetching/using on your system?
    - I built the demo listener app using:  Target system: (PX4 and listener demo): Ubuntu 20.04
        - Fast-RTPS 2.0.2 
        - Fast-RTPS-Gen 1.0.4 ,
        - PX4 started from the master branch.

I looked on which topic, the micrortps_agent publishes the data of the sensors: `fmu/sensor_combined/out` _(px4_firmware/build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_agent)_.

So for the demo "listener application" receive sensor data, you must also change the name of the topic.

**Comment by hamishwillee** [comment]
Thanks @SylvainPastor .

@TSC21 When you have a moment can you please respond/approve. I'm not competent to judge this.

**Comment by TSC21** [comment]
This is correct! Thanks @SylvainPastor

**Review by TSC21 — APPROVED** [review]

**Comment by hamishwillee** [comment]
Thanks very much!

**Pull request merged**
