### PR TITLE
Improve instructions for ignition video

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Problem Description**
Update link for video and add explanation for flags

**Additional Context**
- Adds instructions from the following PR: https://github.com/PX4/PX4-Autopilot/pull/18191 https://github.com/PX4/PX4-Autopilot/pull/18187

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Not sure what the CI failure means - @dagar do we need to disable some of them or is this a real CI failure?

**Comment by dagar** [comment]
> Not sure what the CI failure means - @dagar do we need to disable some of them or is this a real CI failure?

I believe it's real, looking for a solution.

**Comment by hamishwillee** [comment]
The fails are due to doc build size exceeding environment. For the moment I am doing at least one manual build locally every week.

**Comment by hamishwillee** [comment]
Thanks @Jaeyoung-Lim - I'll do a new docs release during the week.

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Thanks!

**Comment by hamishwillee** [comment]
FYI Dan has fixed the docs build.

**Pull request merged**
