### PR TITLE
Document acceleration setpoints for offboard mode

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Problem Description**
This documents the added support of acceleration supports in offboard mode.

Now we can provide acceleration setpoints in combination of position/velocity setpoints. 

This is a documentation of https://github.com/PX4/PX4-Autopilot/pull/15707

### CODE REVIEW

**Review by RicardoM17 — APPROVED** [review]

**Comment by RicardoM17** [comment]
Thanks for updating the docs @Jaeyoung-Lim !

**Comment by RicardoM17** [comment]
@Jaeyoung-Lim Whoops my bad. 😅  @hamishwillee FYI and sorry about the issue.

Not sure if we should revert this or if the PR will be merged soon..

Apologies for the mistake. Forgot to check that one detail. I thought it had been merged already.

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim How long until the PR is likely to merge.

@RicardoM17 You are not the first, and you will not be the last. :-)

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I believe it will be merged fairly soon (hopefully), but not sure when...

**Comment by hamishwillee** [comment]
Well, the choices are do nothing, pull it out, or add a "coming soon" note - based on whether you think it will be months, years or who knows :-)

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I will try to get it in within this week and if it doesn't happen will update the docs with a "coming soon" note. Would this be a viable plan?

**Comment by hamishwillee** [comment]
Awesome!

**Pull request merged**
