### PR TITLE
fix: fix broken link to standards

### PR DESCRIPTION
**Pull request by mnihalm**
Some pages have a broken link to the standards page. This PR fixes that

### CODE REVIEW

**Comment by mrpollo** [comment]
Thanks for your first contribution 🏆  @mnihalm 👏

**Comment by hamishwillee** [comment]
@mnihalm @mrpollo For future reference, please don't modify (or merge) any content that isn't in the /en file path. All the other files like /de/ etc are created automatically by crowdin translation. Often changes like this require a complicated merge process to fix the different sources.

**Comment by mrpollo** [comment]
@hamishwillee sorry I should have known better, anything I can do to make this better? should I revert?

**Comment by mnihalm** [comment]
Thanks @mrpollo !

@hamishwillee , noted. was not aware of that. Will have that in mind for future reference

**Pull request merged**
