### PR TITLE
ATL Mantis Edu Documentation

### PR DESCRIPTION
**Pull request by junwoo091400**
This is a documentation PR for the ATL Mantis Edu, a quadcopter based on Mantis G.

It is not complete yet (MAVSDK usage and some details like vendor links need to be added when available), but with the release of the Mantis Edu.

This restores the #1560 documentation which was reverted by #1705, removes detailed developer instructions (Like Camera software flashing), and adds updated comments on usage.

### CODE REVIEW

**Comment by junwoo091400** [comment]
@hamishwillee Could you please convert this into 'draft'? To avoid accidental merging, thanks!!

**Comment by hamishwillee** [comment]
Thanks @junwoo091400 . Done. What is the trigger for this to merge?

**Comment by junwoo091400** [comment]
Currently there are no appropriate links for the ATL Mantis Edu, since it hasn't been released yet. But also I am testing it often and finding different bugs / inconsistent user experiences, so until the release, I will be constantly updating it!

**Comment by mrpollo** [comment]
hey @hamishwillee once we are ready I'll do the merge on this one, it's pending on quite a lot of things falling into place yet which are sadly non code related.

Thanks for the PR @junwoo091400 looks good

**Comment by hamishwillee** [comment]
What's up with this? Would be great to add this if the product is available

**Comment by junwoo091400** [comment]
I think the product release probably won't be coming :cry: @mrpollo there's no point in having this in if it won't be released right?

**Comment by mrpollo** [comment]
Correct we should close this. 

Thank you for the hard work @junwoo091400

**Pull request closed without merging**
