### PR TITLE
Fix description of simulator ports

### PR DESCRIPTION
**Pull request by murphym18**
Please consider this change to `en/simulation/README.md`.  It more  accurately describes how PX4 and the simulator communicate.

I checked the source code for gazebo, jmavsim and PX4. Both simulators listen and PX4 initiates a TCP connection.

To help with verifying accuracy of this change, I include links to relevant source code.

### In gazebo
- [This is where a TCP socket is created](https://github.com/PX4/PX4-SITL_gazebo/blob/7fda4d311a9daff4bec4f2fe83e63fde0b8f04b0/src/mavlink_interface.cpp#L102)
- [This is where that socket is bound to the port](https://github.com/PX4/PX4-SITL_gazebo/blob/7fda4d311a9daff4bec4f2fe83e63fde0b8f04b0/src/mavlink_interface.cpp#L148)
- [And this is where it listens for a connection from PX4](https://github.com/PX4/PX4-SITL_gazebo/blob/7fda4d311a9daff4bec4f2fe83e63fde0b8f04b0/src/mavlink_interface.cpp#L154)

### In jmavsim
Similar code exists. 
- The bulk of TCP server code is in [this method](https://github.com/PX4/jMAVSim/blob/0a5375a70689aac53143768de9033034f3636022/src/me/drton/jmavsim/TCPMavLinkPort.java#L58-L64)
- The connection is accepted in [this method](https://github.com/PX4/jMAVSim/blob/0a5375a70689aac53143768de9033034f3636022/src/me/drton/jmavsim/TCPMavLinkPort.java#L66-L81)

### In PX4
I also looked at the PX4 source code. The simulator module does most of the work. Using the default startup scripts, [this code initializes the module](https://github.com/PX4/PX4-Autopilot/blob/c0efbe1f9cba86bf112f8b62cc2e35956f30ac1a/src/modules/simulator/simulator.cpp#L83-L89). And that code configures the module to initiate a TCP connection to the simulator. The startup script that invokes the module is [`px4-rc.simulator`](https://github.com/PX4/PX4-Autopilot/blob/master/ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator). And it also indicates that TCP is used.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@julianoes Can you please review?

**Review by julianoes — APPROVED** [review]
PX4 does the `connect()` call, so I guess what you write is correct.

**Comment by hamishwillee** [comment]
Thanks @murphym18 ! (& @julianoes for the review). Merged. This won't appear until I rebuild next week (or CI is fixed)

**Comment by murphym18** [comment]
Cool! I'm glad I could help! 😎

**Pull request merged**
