### PR TITLE
Modify commander-flow-diagram to remove Rattitude mode

### PR DESCRIPTION
**Pull request by hamishwillee**
This modifies the commander diagram in http://docs.px4.io/master/en/concept/flight_modes.html#flight-mode-evaluation-diagram to remove the RATTITUDE. 

- This is a GUESS - needs review from someone who knows changes since.
- Title changes this from being relevant to a "date" to be "From PX4 v1.12"

Follows on from #1106

### CODE REVIEW

**Comment by hamishwillee** [comment]
@bkueng Could you please sanity check this ?

**Comment by bkueng** [comment]
Looks reasonable to me.

FYI the old-style mode switching will be removed anytime soon: https://github.com/PX4/PX4-Autopilot/pull/8999

**Comment by hamishwillee** [comment]
Thanks @bkueng ,

Removing the old-style RC setup will be GREAT (especially for docs). Do you know if the implementation took note of the comments from tubeme? ie. the simple setup is better but needs more than 6 slots.

**Comment by bkueng** [comment]
> Do you know if the implementation took note of the comments from tubeme?

I think not

**Pull request merged**
