### PR TITLE
- add support for ModalAI VOXL Flight to autopilot hardware

### PR DESCRIPTION
**Pull request by modaltb**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@modaltb Looks good. This ready for review?

**Comment by modaltb** [comment]
Yes please!  Thanks @hamishwillee for quick response!

**Comment by hamishwillee** [comment]
Thanks. Looks good. FWIW generally I'd say that some of the images could be reduced in size a little without any loss in fidelity. This is important for people on slower links. I didn't force it this time because none of them were "silly" sizes :-).

**Comment by modaltb** [comment]
Thanks for quick turn and I'll scale down in the future ;)!

**Comment by hamishwillee** [comment]
No worries. I just reduced them myself. Normally it is enough to cut off whitespace around edge and convert to jpeg.

**Pull request merged**
