### PR TITLE
Add descriptions for supported RaccoonLab devices

### PR DESCRIPTION
**Pull request by frontw**
Add descriptions for supported RaccoonLab (http://raccoonlab.co) devices:
- manufacturer-supported FMUv6X Autopilot;
- magnetometer module;
- airspeed sensor;
- barometers;
- rangefinders;
- GNSS modules;
- PWM-ESC adapters and general-purpose DroneCAN and Cyphal/CAN nodes;
- DroneCAN power modules

### CODE REVIEW

**Comment by hamishwillee** [comment]
Closing in favour of  #3295 because this won't let me subedit.

**Comment by hamishwillee** [comment]
@frontw Looks cool. 
For my information, why is the FC manufacturer supported? I.e. it seems to take the standard fmuv6 firmware and is Pizhawk standard compliant according to intro, so what about it is not standard compliant?

**Comment by frontw** [comment]
> @frontw Looks cool. For my information, why is the FC manufacturer supported? I.e. it seems to take the standard fmuv6 firmware and is Pizhawk standard compliant according to intro, so what about it is not standard compliant?

Thanks! I messed up the categories, I guess (I thought Manufacturer-Supported category meant that PX4 does not manufacture or support this autopilot). Since this is a standard autopilot, it should be in Pixhawk Standard/Supported Autopilots.

**Comment by hamishwillee** [comment]
Great. Then can you move it there in https://github.com/PX4/PX4-user_guide/pull/3295 - do a quick test to check you can push changes, otherwise I can do this tomorrow.

**Comment by frontw** [comment]
> Great. Then can you move it there in #3295 - do a quick test to check you can push changes, otherwise I can do this tomorrow.

Nope, `ERROR: Permission to PX4/PX4-user_guide.git denied to frontw.`. 

I tried to move `- [RaccoonLab Autopilot (FMUv6X)](../flight_controller/raccoonlab_fmu6x.md)` to 
 Standard/Supported Autopilots in index.md and delete `info This flight controller is supported by manufacturer` from raccoonlab_fmu6x.md.

Grateful for your help with this

**Comment by hamishwillee** [comment]
All merged. I'm very happy to help people who have clearly already put a lot of work in :-)

**Pull request closed without merging**
