### PR TITLE
VTOL Quad Tailsitter - fix up SVG

### PR DESCRIPTION
**Pull request by hamishwillee**
Fix for VTOL tailsitter image as discussed in https://github.com/PX4/PX4-user_guide/issues/1849#issuecomment-1107692357

### CODE REVIEW

**Comment by hamishwillee** [comment]
This one's for you to confirm @RomanBapst

**Comment by hamishwillee** [comment]
@sfuhrer I'm merging this, but would be great if you could sanity check?

**Comment by sfuhrer** [comment]
Yeah looks a bit clearer, thanks!

**Comment by hamishwillee** [comment]
Thanks Silvan. WOuld be nice if we had a real graphic artist in the house.

**Pull request merged**
