### PR TITLE
Communicating with individual vehicles using ROS2

### PR DESCRIPTION
**Pull request by max11gen**
I added a note on how to publish and subscribe to the topics of a specific instance of PX4 using ROS2. I found the explanation in [this answer](https://discuss.px4.io/t/how-to-isolate-topics-of-different-urtps-agent-if-i-have-multiplel-instance/21576/2) by @TSC21 and thought it might be easier to find for others in the docs.

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]
Thanks!

**Comment by hamishwillee** [comment]
Thanks. So if you don't use `n` you can't subscribe to topic individually? I.e. this is a "have to"?

**Comment by max11gen** [comment]
Exactly. If you don't use the `n` option to assign each vehicle its individual namespace, all vehicles publish to the same topic. Then - when you subscribe to e.g. sensors_combined_pubsub topic - you won't be able to tell which vehicle sent which message. Also if you publish e.g. to the vehicle_command topic, all vehicles will to the same thing. So I would go as far as saying that multivehicle control via ROS2 is not possible without the namespace parameter

**Comment by hamishwillee** [comment]
@max11gen Thanks very much. I've modified the text a bit to make it clear this is "must" rather than "can" in https://github.com/PX4/PX4-user_guide/pull/1374

**Pull request merged**
