### PR TITLE
Create UAHRQ.svg

### PR DESCRIPTION
**Pull request by MridulSengupta**
SVG file

### CODE REVIEW

**Comment by hamishwillee** [comment]
What is this for? The SVG file appears to be invalid.

**Comment by MridulSengupta** [comment]
Dear Hamish,
          Greetings of the day. This is Mridul Sengupta and master's
student of Aerospace Engineering from Indian Institute of Technology Kanpur
in India. We are creating a new airframe group "hybrid" which will contain
drones which are mix of rover and Quadcopter. In that group we are creating
a airframe configuration called Unmanned Autonomous Hybrid Rover Quadcopter
(UAHRQ). I wrote the code for it and built it but now I want to put my
frame in Qgroundcontrol but I am clueless about it. I saw the px4 user
guide documentation in that it was said to put the frame svg file to this
folder of repository, but i am clueless about this like how to show my
frame in Qgroundcontrol. If you can help me in this aspect I would really
appreciate it. Hoping to hear from you soon

Thanks and Regards
Mridul Sengupta

**Comment by hamishwillee** [comment]
Hi @MridulSengupta 

So the first thing you need to do is to create your airframe definition file http://docs.px4.io/main/en/dev_airframes/adding_a_new_frame.html#add-frame-to-qgroundcontrol

The link above shows how, and specifically how to get this into QGC for selection. Initially this will have no icon and you don't need one.

Once you have got PX4-Autopilot to accept this frame in the codeline we can talk more about getting icons and such setup.

**Comment by MridulSengupta** [comment]
Hi Hamish,
                         Are you on discord so that I can correspond
better with you? I have created the defination file for the airframe (can
share you the file) and wishing to create a new group and add that airframe
in newly created airframe group. So for now do I need to follow the steps
whose screenshots I am attaching??? Steps mentioned before the attached
screenshots are executed and successfully built by me. Hoping to hear from
you soon.


Thanks & Regards
Mridul

**Comment by hamishwillee** [comment]
Hi @MridulSengupta 
Not until Wednesday (I'm on other work). This is not a docs issue, so you should raise your discussion on the discussion boards. If no one has answered by then I'll have a look.

**Comment by MridulSengupta** [comment]
Okay, thanks for your support

**Comment by hamishwillee** [comment]
I added note in here https://discord.com/channels/1022170275984457759/1022185721450213396/threads/1157179959585021992

Essentially what you do depends on where you are. The instructions assume that either you are just beginning your frame, in which case you load the configuration from the SD card rather than QGC, OR you are at the end of your development and you are adding the frame to PX4 and QGroundControl for the rest of the community to use - in which case you follow the instructions, and the build toolchain automatically provides metadata to QGC. The instructions don't cover an in between case, such as a custom build of PX4 and custom QGC that includes icons etc.

**Comment by hamishwillee** [comment]
Closing. Too early to add this AFAIK.

**Pull request closed without merging**
