### PR TITLE
Add documentation for #15303

### PR DESCRIPTION
**Pull request by ThomasRigi**

### CODE REVIEW

**Comment by hamishwillee** [comment]
Hi
Can you please remove all the changes to files that are not in the en/ path - e.g. zh, ko etc. These get automatically updated by Crowdin, so if I was to accept these, it would make merging translations a lot harder.

**Comment by ThomasRigi** [comment]
I hope I did it correctly. I don't know where they came from. I thought I only changed one page...

**Review by LorenzMeier — APPROVED** [review]
Thanks!

**Comment by hamishwillee** [comment]
Thanks @ThomasRigi 

If you click the files-changed tab you can see that there are all those other files in different languages: image

This sort of thing happens sometimes. Not sure why - but usually result of making changes to an older version of docs. Usually I fixed it by doing a rebase to master - ie `git rebase upstream/master` 

Anyway, I couldn't fix it in your branch so I recreated this in #995 using your commit. 

Thanks very much!

**Comment by ThomasRigi** [comment]
Ok thanks for the insights. In case it helps to find out why it happened, here is what I did to create this PR: 
Go to https://docs.px4.io/master/en/flight_modes/offboard.html, then "Edit this page on GitHub" on the bottom of the page, change the corresponding offboard file, propose changes. I never worked on my local machine, always in the Github browser window.

**Comment by hamishwillee** [comment]
@ThomasRigi I have no idea then - that's a bit weird. Thanks for letting me know, and for making the change!

**Pull request closed without merging**
