### PR TITLE
Update ROS naming convention

### PR DESCRIPTION
**Pull request by beniaminopozzan**
According to https://discourse.ros.org/t/should-i-put-a-space-between-ros-and-2/27949 the correct naming convention is **ROS 1** and **ROS 2**.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @beniaminopozzan - that's a change - originally the theory was ROS and ROS 2. This new convention is better, though it would be even better as ROS1 and ROS2.

**Comment by beniaminopozzan** [comment]
@hamishwillee at least now we are consistent :)

**Comment by hamishwillee** [comment]
For sure - it's a good thing. Just not as good as it would be if I was in charge. Yes, I'm serious :-)

**Comment by hamishwillee** [comment]
And thanks for sorting this stuff out. I'll review the other stuff next week.

**Pull request merged**
