### PR TITLE
acro_mc.md: Add expo term

### PR DESCRIPTION
**Pull request by whataberk**
Add the expo factor to the cubic term in the exponential describing function. This needs to be merged to 1.9-1.11 too - I can create separate pull requests if necessary? 

#941

### CODE REVIEW

**Comment by hamishwillee** [comment]
@whataberk Thanks! FYI, we generally start by fixing the master version of the docs first. The fix may then be back ported to the last version of the docs

@bresch Does this make sense to you? (does not to me, but then I am probably missing something)

**Comment by whataberk** [comment]
@hamishwillee Would you like me to make a new branch and pull request off of `master`? I'd be happy to. 

The issue I added (#942) and mentioned in the PR noted was that the docs version of the function a) does not match the code and b) does not match the description of the algorithm. That is, if `f` goes to zero in the docs function then you still have a cubic component in the function.

**Comment by hamishwillee** [comment]
@whataberk Let's get @bresch review and I can push it up to master. No point adding work if he has some other opinion. Just a note for next time :-)

**Review by bresch — APPROVED** [review]
That's correct, thanks

**Comment by hamishwillee** [comment]
Thanks @whataberk and @bresch - merged, and I fixed up master, v1.11 and v1.10 in line with this.

**Pull request merged**
