### PR TITLE
Bugfix - made the flighttask links visible

### PR DESCRIPTION
**Pull request by Claudio-Chies**
the old @[youtube] didnt work, just linked the titles to the videos

### CODE REVIEW

**Comment by hamishwillee** [comment]
How have you tested this? The current version fine for me - see https://docs.px4.io/main/en/concept/flight_tasks.html#creating-a-flight-task

image

Note, that this format `@[youtube](https://youtu.be/-dkQG8YLffc)` is supported via
https://www.npmjs.com/package/markdown-it-video

**Comment by Claudio-Chies** [comment]
interesting, what browser do you use? for me it looks like this:
image
on Firefox 128.0

**Comment by hamishwillee** [comment]
Hmmm, Firefox reports an error. I'd tested on chrome. 

image

We'll leave this open - it is important to fix the video rendering rather than patch individual docs. Will have a look at the possible workaround next week.

Thank you.

**Comment by hamishwillee** [comment]
FYI, I'm not a web developers, so even though I know the cause I am not sure of the "right" fix. I've asked in https://github.com/vuejs/vitepress/issues/4053

**Comment by hamishwillee** [comment]
Thanks @Claudio-Chies . After much work I have deployed a new mechanism for video playing that should be better maintained and solid going forward.

https://github.com/PX4/PX4-user_guide/pull/3300

**Comment by Claudio-Chies** [comment]
@hamishwillee Thanks alot!

**Comment by hamishwillee** [comment]
NO, thanks for taking the trouble to report this stuff. I'm sure others must run into it and just ignore the problem

**Pull request closed without merging**
