### PR TITLE
Add Holybro Sik Telemetry radio Info

### PR DESCRIPTION
**Pull request by vincentpoont2**
Add Holybro Sik Telemetry radio Info

### CODE REVIEW

**Comment by hamishwillee** [comment]
@vincentpoont2 

Looks good. Typo here:

image

The big image can be significantly compressed. Here, for example, is about 60% reduction in size with no visible degredation.
holybro_sik_radio_v3_include

**Comment by hamishwillee** [comment]
@vincentpoont2 Hi, did you see my comment here on shrinking the image ^^^ / fixing the typo in the image?

Otherwise good to go.

**Comment by vincentpoont2** [comment]
@hamishwillee fixed! Thanks!

**Comment by hamishwillee** [comment]
Awesome. Thanks very much!

**Pull request merged**
