### PR TITLE
Update Cube Orange Page Detail

### PR DESCRIPTION
**Pull request by chrisksl**
Correct processor from STM32H743ZI to STM32H753VI
Remove Debug Port as it is not available on the latest ADSB Carrier Board

### CODE REVIEW

**Review by julianoes — APPROVED** [review]
Great, thanks for that.

**Comment by proficnc** [comment]
looks good.

**Comment by hamishwillee** [comment]
Hi @chrisksl,

The text changes are good but you have also added two (very large) images that you then do not use. Please delete the images.

Note, if you were to add these images then you would need to move them into the `\assets\flight_controller\cube\orangeplus\` directory and shrink them significantly in terms of file size.

I attached some reduced size versions FYI
ports_usb_sdcard
ports_top_main

Cheers H

**Comment by hamishwillee** [comment]
PS, I'd fix this myself but your fork appears to be blocked against allowing changes, even in PRs.

**Comment by hamishwillee** [comment]
I've taken the content changes in #2425. The images are too big and not used, so not needed in this PR. Closing.

**Pull request closed without merging**
