### PR TITLE
Update holybro_qav250_pixhawk4_mini.md

### PR DESCRIPTION
**Pull request by Ostefanini**
Update qav 250 pixhawk4 mini doc in correspondance with the kit I've just received this week.

Here is the commercial mail associated:
Sorry, due to the change of the motor supplier, the appearance of the motor in the current package is different from that of the previous version.
The new motor has no DX/SX difference.
All the M5nuts are black.

### CODE REVIEW

**Comment by Ostefanini** [comment]
It looks like a very interesting questions ! I haven't finished my build yet, because I will receive some additional components in the next days, but I ''ve added a remind to update the PR right after that.

Since this pull request, I noticed two ther changes:

1. about the radio module wich is now a kit with two module identicals:

http://www.holybro.com/product/transceiver-telemetry-radio-v3-915mhz/

2. about the (optionnal) camera wiring. 

Should I open two other pull requests or just update this one (and change it's title) ?

This frame build tutorial is important as one of the less expensive kit, I will be very happy to participate 👍

**Comment by hamishwillee** [comment]
Hi @Ostefanini 

Feel free to update this PR with the new materials. I agree, this is a good build to keep updated!

**Comment by hamishwillee** [comment]
Hi @Ostefanini 
Any progress on the open questions?

**Comment by Ostefanini** [comment]
Hello, sorry for losing attention Here. You were obviously right, even if the mots are not self oriented, one still needs to ensure clockwise and anti-clockwise spin orientation. It also needs to put propeller in correct orientation.

**Comment by hamishwillee** [comment]
Thanks @Ostefanini. Want to make an update so we can get this in? Something along the lines of "You may get 4 motors with blacks nuts on their top rather than XXXX. In this case you still need to YYYY ?

**Comment by hamishwillee** [comment]
OK. I have decided to close this. You are very welcome to reopen it when you have a moment :-)

**Pull request closed without merging**
