### PR TITLE
Adding Kahuna to ESP8266_wifi_module page

### PR DESCRIPTION
**Pull request by SamJCKnox**
We have developed new hardware and software to support the ESP8266 telemetry modules. Our software is open-source [here](https://github.com/BeyondRobotix/Kahuna) and upgrades the ESP GUI. We have compiled comprehensive documentation on our [website](https://www.beyondrobotix.com/products/kahuna) that should make using WiFi with any autopilot much more accessible. We are avid Ardupilot enthusiasts and hope to help contribute to this great cause.

### CODE REVIEW

**Review by hamishwillee — APPROVED** [review]
@SamJCKnox - your enthusiasm for ArduPilot on the PX4 docs site amuses me :-). 

Thanks very much for this. I did a minor subedit to my taste. Includes a link to your user guide because that seems to have the details for the wifi network.

**Comment by hamishwillee** [comment]
PS For reference, if you should contribute here again, would you mind branching your main branch and pushing the new branch to a PR? That makes it a little easier for me to edit locally.

ie.
```
git checkout main
git pull upstream main
git checkout -b my_new_branch

... do work and commit

git push upstream my_new_branch
```

**Comment by SamJCKnox** [comment]
@hamishwillee Thank you very much, absolutely I will add to a new branch next time, thank you for the code snippets :) My mistake on the Ardupilot comment haha! Thanks again :)

**Comment by hamishwillee** [comment]
>  My mistake on the Ardupilot comment haha! 

Easily done - also a good flight stack with an great dev team and community.

**Pull request merged**
