### PR TITLE
Add Balloon group image 

### PR DESCRIPTION
**Pull request by kaklik**
A new airframe group image related to [the balloon airframe](https://github.com/PX4/PX4-Autopilot/pull/16632). 

Balloon svg

### CODE REVIEW

**Comment by hamishwillee** [comment]
Can you please rebase - this has 20 irrelevant commits included in it.

**Comment by dagar** [comment]
> Can you please rebase - this has 20 irrelevant commits included in it.

"Squash and merge" works well for this if you want the entire final change.

Screen Shot 2021-02-01 at 4 07 21 PM

**Comment by hamishwillee** [comment]
@dagar The commits appear to have nothing to do with this PR - ie they appear to have been pulled in from merges. They don't affect the fie itself. I would have expected just one commit for the just the one file. 
But if you say so, happy to  just rebase.

**Comment by kaklik** [comment]
> @dagar The commits appear to have nothing to do with this PR - ie they appear to have been pulled in from merges. They don't affect the fie itself. I would have expected just one commit for the just the one file.
> But if you say so, happy to just rebase.

Ok, I could try to squash commits on our side. But how is the best practice to avoid this pilling up of our "inrelevant" commits in pull-requests which are already part of previous pull-requests?  This is the result of merge upstream master to our master and then merge with the modified branch. Therefore at least the  "Merge remote-tracking branch 'upstream/master' " commits are unavoidable in that workflow.

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
Squashed into one clean commit (one click squash & merge).

Screenshot from 2021-02-01 17-34-58

**Comment by hamishwillee** [comment]
Thanks!

**Pull request merged**
