### PR TITLE
[WIP] Add VTOL and plane for GZ simulation

### PR DESCRIPTION
**Pull request by jmackay2**

### CODE REVIEW

**Review by Jaeyoung-Lim — APPROVED** [review]
Thanks!

**Comment by hamishwillee** [comment]
@jmackay2 That's very cool - I'm a bit out of the loop on Gazebo "that used to be Ignition". Did not know about new vehicles.

Any chance you could create a page like this one, but for Gazebo? http://docs.px4.io/main/en/sim_gazebo_classic/gazebo_vehicles.html

@Jaeyoung-Lim I've made you reviewer on this

**Comment by hamishwillee** [comment]
Ah, we should also add this information here: http://docs.px4.io/main/en/simulation/#supported-simulators

@Jaeyoung-Lim Do you happen to know if you can do multi vehicle simulations with plane/vtol or mixtures of vehicle types?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee I think this needs improvements on the gazebonside ehich might not be available on the current distributed version.

So I would not have it in the docs for now. I will add them to the docs when I am happy with the status.

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim You mean "don't merge this yet"? OK. I've set to WIP in title and put as draft.

Any kind of ETA when I should nag to see if this has been done?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee no no I think this is good to go. My comment was on the multivehicle/mixed vehicle in the new gazebo

**Comment by hamishwillee** [comment]
Great. I'll update the simulators page. Would appreciate it if you can create a vehicle page as indicated above @jmackay2 . Up to you though!

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim Would be good if you could update http://docs.px4.io/main/en/sim_gazebo_gz/#usage-configuration-options with the right values for PX4_SYS_AUTOSTART - i.e. it isn't clear to me if this would work for cessna and standard vtol

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Sure!

**Pull request merged**
