### PR TITLE
Docs(zh): fix tip block error

### PR DESCRIPTION
**Pull request by veaba**
Tip element block should be new line.

### CODE REVIEW

**Comment by veaba** [comment]
It shouldn't be here.

image

**Comment by hamishwillee** [comment]
Thank you, but we can't fix the problem in this way. The translations have to go through crowdin - as described here: http://docs.px4.io/main/en/contribute/translation.html

Otherwise we will end up with lots of sync errors.

You're welcome to join those projects and fix it there!

**Comment by hamishwillee** [comment]
I've updated the section, losing some translation, but fixing this error.

**Comment by hamishwillee** [comment]
Sorry you're confused. Crowdin is a tool designed for managing translations. It takes the English docs, you provide translation, and it spits out the translated docs. What is cool about this is that it provides you with hints, and if the English docs update, then the translations that were incorrect are lost. That's a good thing - it means that there can be incomplete translations, but not "old translations that are wrong".

**Comment by veaba** [comment]
I will try how use it.

**Pull request closed without merging**
