### PR TITLE
Update flight_tasks.md

### PR DESCRIPTION
**Pull request by NourElMenshawy**
using trajectory setpoint

### CODE REVIEW

**Comment by hamishwillee** [comment]
@MaEtUgR Does this make sense to you ?

**Comment by MaEtUgR** [comment]
@hamishwillee Yes! By now we use the reference of the topic :+1: 
@NourElMenshawy Thanks for the fix :pray: 
Reference: https://github.com/PX4/PX4-Autopilot/blob/794d0d177bf526a83b94c23f36b674f961955200/src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp#L84

**Comment by hamishwillee** [comment]
Thanks both!

**Comment by NourElMenshawy** [comment]
I'm delighted to be of assistance. I eagerly anticipate contributing more merge requests to the code base from my end.

**Pull request merged**
