### PR TITLE
Update and rename adding_a_new_frame.md babyshark config

### PR DESCRIPTION
**Pull request by sfuhrer**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@sfuhrer FYI, this broke the build, because the summary links to it.

More important, was it it intentional? The topic is "# Adding a Frame Configuration" - why would you move it?

**Comment by hamishwillee** [comment]
PS I'm moving it back!

**Comment by sfuhrer** [comment]
The renaming wasn't intentional, thanks for fixing it!

**Comment by hamishwillee** [comment]
No worries. Easily done. Thanks so much for all these fixes - docs starting to look accurate again.

**Pull request merged**
