### PR TITLE
Update ros2_offboard_control.md

### PR DESCRIPTION
**Pull request by 96moustafa**
updated the docs of offboard mode to match the changes to offboard_control.cpp file as discussed [here](https://github.com/PX4/px4_ros_com/pull/71)

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]
LGTM! Thanks! @hamishwillee any last check?

**Comment by hamishwillee** [comment]
Is this going into PX4 v1.12? If not, then need to time merging.

**Comment by TSC21** [comment]
> Is this going into PX4 v1.12? If not, then need to time merging.

I honestly don't think it will go to 1.12. But what limits this being brought in? Can't we branch off already to 1.12?

**Comment by hamishwillee** [comment]
> I honestly don't think it will go to 1.12. Thought this is something changed in px4_ros_com. But what limits this being brought in? Can't we branch off already to 1.12?

No.

Since nothing new in the release notes for v1.12 has been documented. Time for the dev team to get to work on this. I kicked off a discussion on this last week. Still waiting on responses.

**Comment by mrpollo** [comment]
Just wanted to clarity that the offboard changes are already in master, and are part of the v1.12 feature set, I haven't had the opportunity to finish the release notes, but will get there soon.

**Comment by hamishwillee** [comment]
Thanks for clarification @mrpollo . I will merge. FWIW that this [adds the new message](https://github.com/PX4/PX4-Autopilot/commit/6914ebef4e5ff602885c4ac689aaa6956f0a30fc) but the old one is still present. 

Thank you @96moustafa !

**Pull request merged**
