### PR TITLE
Created UA version for PX4 User Guide documentation

### PR DESCRIPTION
**Pull request by tomkaXX**
Created UA version for PX4 User Guide documentation
- translated the main readme in Ukrainian
- added UA folder for Crowdin

### CODE REVIEW

**Comment by tomkaXX** [comment]
UA folder was copied from EN version - set from  latest and most modified version at the moment. 
Crowdin does not allow adding language until a specific folder appears in the project.

**Comment by tomkaXX** [comment]
Is anyone alive to merge it? Would love to start with Crowdin and translate it all. ASAP

**Comment by hamishwillee** [comment]
NOrmally you ask for a translation folder in crowdin first - we create the folder in Crowdin if we want to. I'd prefer to do it that way.

How much time do you have to devote to translations/do you have other team members? Translation works better if there is a person to review other member's work. 

My concern here is that often we have an enthusiastic user who starts off, translates 2 pages and disappears. The translation is then in the tree but isn't big enough to build (each translation slows the build, so we only build them when they are complete enough. We currently have 4 unbuilt translations).

**Comment by tomkaXX** [comment]
I do not have access to Crowdin to add languages( only contribute to Russian)

**Comment by hamishwillee** [comment]
@tomkaXX Thanks very much. So here is an invite link to Crowdin for this project _as a translator_ https://crowdin.com/project/px4-user-guide/invite?h=c668d25621748ec6bb1bc511f52654101984838 - the folder is created.  you'd have to manually retranslate whatever is done in this PR sorry. You can share this with your authors.

Do you want to act as approver for other's translations? If so I can give you that right once you log in.

If there isn't enough activity I may delete any translations at some point.

**Comment by tomkaXX** [comment]
Do you want to act as approver for other's translations? 
-yes, please for Ukrainian version

**Comment by hamishwillee** [comment]
Sure, click the link, join the project and I'll upgrade your login.

**Comment by tomkaXX** [comment]
I fully translate the main Readme into Ukrainian. 
How does further process work? published when all ready? or review file by file? or I need assign someone to review?

**Comment by hamishwillee** [comment]
All translations have to be done here: https://crowdin.com/project/px4-user-guide/uk

Any translations that you do will be pushed to a PR on the user guide, which I merge weekly. This then is available in the tree, but I won't build a translation until it is "significant" - at least 10%.

However there is nothing to stop you taking the sources at any point and hosting your own build of this for a ukranian audience.

Crowdin can be set to export any translation or only approved translations. I _think_ I allow any translation to be published, but I much prefer it when translations are reviewed and then approved by different people.

**Comment by mcsauder** [comment]
I agree with @hamishwillee . His discourse is self explanatory.

**Comment by hamishwillee** [comment]
Closing this now. @tomkaXX When you've clicked the invite link I'll grant you access.

**Comment by mrpollo** [comment]
Let us know if you need help @tomkaXX

**Pull request closed without merging**
