### PR TITLE
Dronecan Holybro F9P Param change fix

### PR DESCRIPTION
**Pull request by dirksavage88**
@hamishwillee  Param changed to match the actual new parameter: https://github.com/PX4/PX4-Autopilot/pull/23821/files#diff-de800df88a6874ed094f72d78d51c1c061851ce99d07fd2497788f5fb82a2ee8

- [x] https://github.com/PX4/PX4-Autopilot/pull/23821

### CODE REVIEW

**Comment by hamishwillee** [comment]
When you're ready for review, please ping me.

Note, is it that `GPS_YAW_OFFSET` replaces `EKF2_GPS_YAW_OFF` or that this particular document was wrong, and it just said the wrong parameter?

I ask because `GPS_YAW_OFFSET` appears in many places in the docs - so if it is being removed we need to fix all of them.
Result of search below on my local drive.

<details>
  D:\github\px4\PX4-user_guide\en\advanced_config\parameter_reference.md (2 hits)
	Line 18125: ### GPS_YAW_OFFSET (`FLOAT`) {#GPS_YAW_OFFSET}
  D:\github\px4\PX4-user_guide\en\dronecan\ark_rtk_gps.md (4 hits)
	Line 106:   - [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET) to `0` if your _Rover_ is in front of your _Moving Base_, `90` if _Rover_ is right of _Moving Base_, `180` if _Rover_ is behind _Moving Base_, or `270` if _Rover_ is left of _Moving Base_.
	Line 126:   - [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET) to `0` if your _Rover_ is in front of your _Moving Base_, `90` if _Rover_ is right of _Moving Base_, `180` if _Rover_ is behind _Moving Base_, or `270` if _Rover_ is left of _Moving Base_.
  D:\github\px4\PX4-user_guide\en\dronecan\holybro_h_rtk_zed_f9p_gps.md (2 hits)
	Line 117: - [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET): Set to the clockwise angle (degrees) corresponding to base and rover orientation (e.g. 90 degrees when moving base to the left and rover to the right)
  D:\github\px4\PX4-user_guide\en\dronecan\index.md (2 hits)
	Line 215: For PX4 you will also need to set [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET) to indicate the relative position of the moving base and rover: 0 if your Rover is in front of your Moving Base, 90 if Rover is right of Moving Base, 180 if Rover is behind Moving Base, or 270 if Rover is left of Moving Base.
  D:\github\px4\PX4-user_guide\en\gps_compass\rtk_gps.md (4 hits)
	Line 164: | [GPS_YAW_OFFSET][GPS_YAW_OFFSET] | The angle made by the _baseline_ (the line between the two GPS antennas) relative to the vehicle x-axis (front/back axis, as shown [here][fc_orientation]). |
	Line 169: [GPS_YAW_OFFSET]: ../advanced_config/parameter_reference.md#GPS_YAW_OFFSET
  D:\github\px4\PX4-user_guide\en\gps_compass\rtk_gps_fem_mini2.md (2 hits)
	Line 46: The direction that they are facing does not matter as it can be configured with the [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET) parameter.
  D:\github\px4\PX4-user_guide\en\gps_compass\rtk_gps_holybro_unicore_um982.md (2 hits)
	Line 57: - [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET): Set heading offset to 0 if the primary antenna is in the front.
  D:\github\px4\PX4-user_guide\en\gps_compass\rtk_gps_trimble_mb_two.md (3 hits)
	Line 55: The direction that they are facing does not matter as it can be configured with the [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET) parameter.
	Line 58: The `GPS_YAW_OFFSET` is the angle made by the *baseline* (the line between the two GPS antennas) relative to the vehicle x-axis (front/back axis, as shown [here](../config/flight_controller_orientation.md#calculating-orientation)).
  D:\github\px4\PX4-user_guide\en\gps_compass\u-blox_f9p_heading.md (4 hits)
	Line 28: - The antennas can be positioned as needed, but the [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET) must be configured:
	Line 40: - [GPS_YAW_OFFSET](../advanced_config/parameter_reference.md#GPS_YAW_OFFSET) may need to be set (see [RTK GPS > GPS as Yaw/Heading Source](../gps_compass/rtk_gps.md#configuring-gps-as-yaw-heading-source)).
	</details>

**Comment by dirksavage88** [comment]
@hamishwillee we are just waiting on the PR to get merged. It's been reviewed and approved.

The existing GPS_YAW_OFFSET param will remain for the serial driver implementation, but we are adding EKF2_GPS_YAW_OFFSET just for the dronecan nodes (eventually we hope to have px4 cannode also publish to the actual dronecan heading fields, not just ap periph)

**Comment by hamishwillee** [comment]
That's great - can you check the documented cases and make sure that they all refer to the correct parameter?

**Comment by dirksavage88** [comment]
@hamishwillee this new param is solely for the DroneCAN Dual GPS heading that run the AP periph firmware, so the other (serial and PX4 cannode) cases are un-affected

**Review by hamishwillee — APPROVED** [review]
Thanks very much @dirksavage88 !

**Pull request merged**
