### PR TITLE
Update and rename motion-capture-vicon-optitrack.md to motion-capture…

### PR DESCRIPTION
**Pull request by sage0357**
…-vicon-nokov-optitrack.md

### CODE REVIEW

**Comment by hamishwillee** [comment]
I'm sure NOKOV _can_ be used with PX4 for motion capture, but is there any evidence that it has been?

My concern is that if we put this in there is an assumption that it can be made to work without changes to PX4, and we need that confirmed.

**Comment by sage0357** [comment]
Hi Hamish,

We found some paper of our costomers like Tongji Univertisy and Sun Yat-sen University,in which mentioned their system framework including PX4 and NOKOV Mocap.I attatched pics of the content and links of these papers.

link1:https://arxiv.org/abs/2201.06645
link2:https://www.cnki.com.cn/Article/CJFDTotal-JZJY201909008.htm

If it is not enough, please let me know.Thanks.


***@***.***
 
发件人： Hamish Willee
发送时间： 2022-04-08 06:26
收件人： PX4/PX4-user_guide
抄送： sage0357; Author
主题： Re: [PX4/PX4-user_guide] Update and rename motion-capture-vicon-optitrack.md to motion-capture… (PR #1840)
I'm sure NOKOV can be used with PX4 for motion capture, but is there any evidence that it has been?
My concern is that if we put this in there is an assumption that it can be made to work without changes to PX4, and we need that confirmed.
―

**Comment by hamishwillee** [comment]
Thanks @sage0357 - I can't access those papers and they don't mention NOKOV.

@TSC21 Do you know anyone who has used NOKOV and ROS/PX4 for MoCap? Or enough to know that it is likely to work? I suspect it probably gets abstracted by ROS anyway so should "just work", but since I don't know, trying to do due diligence before merging this.

**Comment by hamishwillee** [comment]
@TSC21 I am merging this. If you have some reason to believe NOKOV does not work let me know and I will revert.

**Pull request merged**
