### PR TITLE
Update dev_env_mac.md

### PR DESCRIPTION
**Pull request by dlech**
https://github.com/PX4/PX4-Autopilot/issues/17644 has been closed, so this can be removed as stated in the note.

### CODE REVIEW

**Comment by dlech** [comment]
OK. maybe the issue is not fixed yet

**Comment by hamishwillee** [comment]
@richtong @dlech I'm confused - is the text still needed or not?

**Comment by dlech** [comment]
Yes, it is still needed. I guess they closed the issue since the note with the workaround was added in the docs and not because the root issue was actually fixed.

**Comment by hamishwillee** [comment]
Thanks. I've reopened the other issue so we can explore whether the instructions just need to live in the docs forever.

**Pull request closed without merging**
