### PR TITLE
added svg for vectored 6 dof uuv airframe

### PR DESCRIPTION
**Pull request by lennartalff**
Followed the [user guide](https://docs.px4.io/master/en/dev_airframes/adding_a_new_frame.html#adding-a-new-airframe-group) to complete the "new" airframe group for the vectored 6 DOF UUV airframe.

Related PRs:
- PX4/PX4-Autopilot#17434
- mavlink/qgroundcontrol#9604

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks. Looks good.

**Comment by hamishwillee** [comment]
PS @lennartalff I don't have any other information on this frame - it would be great to have some more information about it.

For example:
1. Some cool images.
2. Videos of it flying.
3. A build log explaining how you can build one yourself. 

Is that something you could help us create?

**Comment by lennartalff** [comment]
I have used the BlueROV2 as a vehicle of this airframe group. Maybe @DanielDuecker can provide some images/videos.

**Comment by hamishwillee** [comment]
Great! Essentially I'm trying to do two things. Firstly show that you can work with a lot of vehicles on PX4 and show them off. Secondly to make the content reusable for the community (which may or may not apply in this case).

**Comment by DanielDuecker** [comment]
Sure, 

@hamishwillee I could offer the below for the moment.
shall we open a new category in the airframe docs ? Underwater robots or similar?

https://www.youtube.com/watch?v=1sUaURmlmT8 

videos with more action will come soon

The BlueRov Platform in its heavy configuration (8 thrurster)
BlueRov_heavy
Field testing in  Hamburg Finkenwerder Marina
BlueRov_finkenwerder
BlueRov_finkenwerder_1

**Comment by hamishwillee** [comment]
Thanks @DanielDuecker . I am off for a few days, but on my return I will think about this. 

Yes, I think we should have a new category for managing underwater vehicles - probably for now just a section here: https://docs.px4.io/master/en/airframes/
And probably add this to https://docs.px4.io/master/en/complete_vehicles/ (assuming you sell them?)

Longer term I want to play with the airframes section to make it less "Airframes reference" and "Build logs" and more - this is your starting point for different classes of airframes.

If you want to take this offline at some point fell free to ping me on PX4 slack (hamishwillee) or email me (same but at gmail).

**Comment by hamishwillee** [comment]
PS BTW, docs updated with this now https://docs.px4.io/master/en/airframes/airframe_reference.html#vectored-6-dof-uuv

**Comment by hamishwillee** [comment]
@DanielDuecker I was wondering if you could review my proposed update in #1236?

It should basically be OK '"as is" but very minimal - so the description has some questions that could help make this more useful.

**Pull request merged**
