### PR TITLE
delete all mentions of rattitude flight mode

### PR DESCRIPTION
**Pull request by dagar**
Deleted in https://github.com/PX4/PX4-Autopilot/pull/17019.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dagar Those merge conflicts are because the content for the translations round trip via Crowdin for translation. Can you remove all changes to those files? Alternatively i will recreate this change on Wednedsay.

**Comment by dagar** [comment]
Done.

**Comment by hamishwillee** [comment]
I don't see any changes @dagar . Essentially the only files still here should be the ones in the /en/ folder.

**Comment by dagar** [comment]
> I don't see any changes @dagar . Essentially the only files still here should be the ones in the /en/ folder.

Mulligan.

**Comment by hamishwillee** [comment]
Thanks @dagar 

Merging. Do you happen to know if there is source for the image at the bottom of the development topic - which still mentions RATTITUDE http://docs.px4.io/master/en/concept/flight_modes.html#flight-mode-evaluation-diagram

**Pull request merged**
